### ISSUE TITLE
DevManager functionality

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/react-native#42] opened 2015-12-28 14:17 UTC
This should include things like exception handling, debugging, etc.

**Comment by rozele** [comment] 2016-01-26 03:15
This issue is very broad. It includes everything from debugging, loading JavaScript from a dev server, "hot" reloading of the JavaScript bundle, and red box exceptions.

**Comment by rozele** [comment] 2016-01-27 14:07
RedBox is in a rough initial state #138.

**Comment by rozele** [comment] 2016-02-18 13:57
This is too broad, live reloading is already supported, we need additional bugs for the fine-grained tasks (like Chrome debugging).  Closing as dupe of pending granular bugs.

**Closed** 2016-02-18 13:57 UTC
Labels: duplicate
